In [2]:
import numpy as np
import pandas as pd

# 1. How likely is it that you roll doubles when rolling two dice?

In [29]:
outcome1 = [1, 2, 3, 4, 5, 6]

outcome2 = [1, 2, 3, 4, 5, 6]

nsimulations = 10_000

roll1 = np.random.choice(outcome1, nsimulations)

roll2 = np.random.choice(outcome2, nsimulations)

In [30]:
roll1

array([4, 5, 3, ..., 3, 1, 3])

In [31]:
roll2

array([4, 5, 2, ..., 2, 2, 1])

In [33]:
doubles = roll1 / roll2 == 1

doubles

array([ True,  True, False, ..., False, False, False])

In [34]:
doubles.mean()

0.1692

# 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [35]:
outcomes = [1, 0]

# 1 == Heads

# 0 == Tails

nsimulations = 10_000

ntrials = 8

flips = np.random.choice(outcomes, size=(nsimulations, ntrials))

flips

array([[1, 1, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 0, 1, ..., 0, 1, 0],
       [1, 1, 0, ..., 1, 0, 1],
       [1, 1, 1, ..., 1, 0, 1]])

In [37]:
num_of_heads = flips.sum(axis=1)

In [38]:
(num_of_heads == 3).mean()

0.223

In [39]:
(num_of_heads > 3).mean()

0.6349

# 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [40]:
outcomes = [1, 0]

# 1 == Data Science

# 0 == Web Development

nsimulations = 10_000

ntrials = 2

billboards = np.random.choice(outcomes, size=(nsimulations, ntrials), p=[.25, .75])

billboards

array([[0, 1],
       [0, 0],
       [0, 1],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]])

In [41]:
ds_billboards = billboards.sum(axis = 1)

ds_billboards

array([1, 0, 1, ..., 0, 0, 0])

In [42]:
(ds_billboards == 2).mean()

0.0607

# 4. Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon?

In [43]:
poptarts = 17

days = 5

nsimulations = 10_000

poptarts_bought = np.random.normal(3, 1.5, size=(nsimulations, days))

poptarts_bought

array([[2.62737893, 1.37792165, 2.27579492, 3.98796213, 3.18173694],
       [6.88618416, 4.79501667, 0.62833958, 2.14274895, 5.34998055],
       [0.44382271, 2.88460282, 3.05919727, 0.91132966, 2.05606946],
       ...,
       [2.10638463, 1.3859063 , 4.5823953 , 3.26610521, 3.29549891],
       [2.92839535, 4.89720657, 1.35907664, 3.44227704, 4.00126262],
       [4.71138041, 2.33976592, 1.5360785 , 3.00328418, 4.57249981]])

In [44]:
poptarts_left = poptarts - poptarts_bought.sum(axis = 1)

poptarts_left

array([ 3.54920544, -2.80226991,  7.64497808, ...,  2.36370965,
        0.37178178,  0.83699118])

In [45]:
(poptarts_left >= 1).mean()

0.6175

# 5. Compare Heights

## Men have an average height of 178 cm and standard deviation of 8cm.

## Women have a mean of 170, sd = 6cm.

## If a man and woman are chosen at random, P(woman taller than man)?