In [3]:
import numpy as np
import pandas as pd

# Mage Duel!

## Let's use what we've learned to play a mage duel!

## Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

## Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

# Exercises

## Simulate mage duels to answer who is the more powerful mage?

## Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.

## Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?

## Do the results change much at 100 duels?

## Now, simulate 10,000 mage duels. Is there a clear winner?

In [1]:
d4 = [1, 2, 3, 4]

d6 = [1, 2, 3, 4, 5, 6]



## Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.

I expect my mage to win

## Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?

I have 10% chance of winning

In [4]:
your_health_rolls = np.random.choice(d4, size = (10, 6))

your_health_rolls

array([[3, 1, 3, 3, 2, 3],
       [4, 1, 3, 1, 1, 1],
       [1, 3, 4, 4, 2, 3],
       [1, 4, 1, 2, 2, 3],
       [1, 3, 2, 4, 4, 3],
       [1, 2, 3, 2, 4, 1],
       [4, 4, 2, 2, 1, 2],
       [4, 3, 2, 3, 4, 2],
       [2, 1, 4, 1, 1, 3],
       [4, 1, 3, 3, 3, 1]])

In [5]:
your_health = your_health_rolls.sum(axis = 1)

your_health

array([15, 11, 17, 13, 17, 13, 15, 18, 12, 15])

In [6]:
enemy_health_rolls = np.random.choice(d6, size = (10, 4))

enemy_health_rolls

array([[6, 5, 3, 1],
       [1, 5, 2, 4],
       [6, 4, 4, 3],
       [2, 5, 3, 5],
       [4, 6, 6, 6],
       [6, 1, 5, 1],
       [4, 6, 4, 4],
       [4, 3, 1, 3],
       [6, 4, 5, 3],
       [4, 3, 1, 4]])

In [7]:
enemy_health = enemy_health_rolls.sum(axis = 1)

enemy_health

array([15, 12, 17, 15, 22, 13, 18, 11, 18, 12])

In [8]:
your_damage_rolls = np.random.choice(d4, size = (10, 6))

your_damage_rolls

array([[1, 4, 3, 1, 1, 3],
       [4, 2, 2, 1, 3, 3],
       [3, 1, 3, 3, 2, 1],
       [3, 2, 1, 2, 3, 1],
       [2, 4, 4, 4, 1, 3],
       [3, 1, 2, 3, 4, 3],
       [4, 3, 2, 4, 1, 4],
       [1, 2, 1, 3, 4, 4],
       [1, 2, 2, 4, 3, 1],
       [2, 4, 1, 1, 1, 3]])

In [9]:
your_damage = your_damage_rolls.sum(axis = 1)

your_damage

array([13, 15, 13, 12, 18, 16, 18, 15, 13, 12])

In [10]:
enemy_damage_rolls = np.random.choice(d6, size = (10, 4))

enemy_damage_rolls

array([[6, 5, 3, 2],
       [3, 5, 3, 1],
       [6, 5, 3, 5],
       [3, 3, 2, 2],
       [6, 1, 3, 1],
       [3, 1, 2, 1],
       [1, 1, 6, 3],
       [6, 6, 4, 3],
       [1, 2, 1, 2],
       [5, 3, 6, 3]])

In [11]:
enemy_damage = enemy_damage_rolls.sum(axis = 1)

enemy_damage

array([16, 12, 19, 10, 11,  7, 11, 19,  6, 17])

In [13]:
you_win = ((your_health > enemy_damage) & (enemy_health < your_damage)).mean()

you_win

0.1

## Do the results change much at 100 duels?

In [14]:
your_health_rolls = np.random.choice(d4, size = (100, 6))

your_health = your_health_rolls.sum(axis = 1)

enemy_health_rolls = np.random.choice(d6, size = (100, 4))

enemy_health = enemy_health_rolls.sum(axis = 1)

your_damage_rolls = np.random.choice(d4, size = (100, 6))

your_damage = your_damage_rolls.sum(axis = 1)

enemy_damage_rolls = np.random.choice(d6, size = (100, 4))

enemy_damage = enemy_damage_rolls.sum(axis = 1)

you_win = ((your_health > enemy_damage) & (enemy_health < your_damage)).mean()

you_win

0.31

## Now, simulate 10,000 mage duels. Is there a clear winner?

In [15]:
your_health_rolls = np.random.choice(d4, size = (10_000, 6))

your_health = your_health_rolls.sum(axis = 1)

enemy_health_rolls = np.random.choice(d6, size = (10_000, 4))

enemy_health = enemy_health_rolls.sum(axis = 1)

your_damage_rolls = np.random.choice(d4, size = (10_000, 6))

your_damage = your_damage_rolls.sum(axis = 1)

enemy_damage_rolls = np.random.choice(d6, size = (10_000, 4))

enemy_damage = enemy_damage_rolls.sum(axis = 1)

you_win = ((your_health > enemy_damage) & (enemy_health < your_damage)).mean()

you_win

0.3028