In [3]:
%matplotlib inline
import numpy as np
import pandas as pd


np.random.seed(29)

# Carnival Dice Rolls

In [5]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4, 5],
       [6, 3, 1],
       [1, 2, 2],
       ...,
       [6, 2, 1],
       [3, 4, 3],
       [4, 2, 4]])

In [6]:
sums_by_trial = rolls.sum(axis=1)
sums_by_trial

array([15, 10,  5, ...,  9, 10, 10])

In [8]:
wins = sums_by_trial > 12
wins

array([ True, False, False, ..., False, False, False])

In [9]:
win_rate = wins.astype(int).mean()
win_rate

0.2633

In [10]:
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

-1.0505000000000004

In [11]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.5860000000000003

# No Rest or Relaxation

In [12]:
p_nap = .3
ndays = ncols = 2
n_simulated_weekends = nrows = 10**5

In [13]:
data = np.random.random((nrows, ncols))
data

array([[0.46762045, 0.70078355],
       [0.18897809, 0.54312897],
       [0.253291  , 0.43836437],
       ...,
       [0.15008559, 0.37577491],
       [0.34690321, 0.58934311],
       [0.97135998, 0.57219933]])

In [14]:
naps = data < p_nap
naps

array([[False, False],
       [ True, False],
       [ True, False],
       ...,
       [ True, False],
       [False, False],
       [False, False]])

In [15]:
naps.sum(axis=1)

array([0, 1, 1, ..., 1, 0, 0])

In [16]:
(naps.sum(axis=1) >= 1).mean()

0.50998

In [17]:
(naps.sum(axis=1) == 0).mean()

0.49002

# One With Dataframes

In [18]:
n_simulations = nrows = 10**5
n_dice_rolled = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], nrows * ncols).reshape(nrows, ncols)

(pd.DataFrame(rolls)
 .apply(lambda row: 3 in row.values, axis=1)
 .mean())

0.42324